sudo: required
services:
  - docker

before_install:
  - docker build -t agamblin/area-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run agamblin/area-react-test yarn test --coverage

after_success:
  - docker build -t agamblin/area-client ./client
  - docker build -t agamblin/area-server ./server
  - docker build -t agamblin/area-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push agamblin/area-client
  - docker push agamblin/area-server
  - docker push agamblin/area-nginx
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'area'
  env: 'area'
  bucket_name: 'elasticbeanstalk-eu-west-3-537685808258'
  bucket_path: 'area'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
