version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 9uOxHyH9
      MYSQL_DATABASE: 'tribe'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8081:80'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '8080:8080'
    environment:
      - SQL_HOST=mysql
      - SQL_USER=root
      - SQL_PASSWORD=9uOxHyH9
      - SQL_DB=tribe
      - SQL_PORT=3306
      - JWT_SECRET=somedumbjwtsecret
      - GITHUB_ID=6c1112c8bc90ffd689ac
      - GITHUB_SECRET=4c16e5c4668feae87847aa0bad457b2bd411b217
      - GITHUB_REDIRECT_URI=http://localhost:8081/api/auth/oauth/github/callback
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - REACT_APP_GITHUB_ID=6c1112c8bc90ffd689ac
      - REACT_APP_GITHUB_SECRET=4c16e5c4668feae87847aa0bad457b2bd411b217
      - REACT_APP_GITHUB_REDIRECT_URI=http://localhost:8081/api/auth/oauth/github/callback
